#pragma once

#define BT_BAUD_RATE 9600UL
#define BT_STATE_ACTIVE_HIGH 1

#define STARTUP_DURATION_MS 2000UL
#define COMMAND_TIMEOUT_MS 1000UL
#define TELEMETRY_PERIOD_MS 500UL
#define DEFAULT_MOTOR_SPEED 170U

#define MOTOR_LEFT_REVERSED 0
#define MOTOR_RIGHT_REVERSED 1

#define MPU_PERIOD_MS 40UL
#define ULTRASONIC_PERIOD_MS 90UL
#define GAS_PERIOD_MS 300UL
#define LIGHT_PERIOD_MS 250UL
#define DHT_PERIOD_MS 2000UL
#define PIR_STARTUP_MS 30000UL

#define ULTRASONIC_MIN_CM 2U
#define ULTRASONIC_MAX_CM 400U
#define ULTRASONIC_VALID_READINGS_REQUIRED 3U
#define ULTRASONIC_FAILURE_LIMIT 3U
#define ULTRASONIC_FAILSAFE_BLOCK_FORWARD 1
#define OBSTACLE_WARNING_CM 30U
#define OBSTACLE_CRITICAL_CM 10U

#define TEMP_WARNING_C 45
#define TEMP_CRITICAL_C 60
#define TEMP_CRITICAL_READINGS_REQUIRED 2U

#define GAS_WARMUP_MS 60000UL
#define GAS_BASELINE_ADC 250U
#define GAS_WARNING_ABOVE_BASELINE 80U
#define GAS_CRITICAL_ABOVE_BASELINE 200U
#define GAS_FILTER_DIVISOR 4U

#define SOUND_SAMPLE_WINDOW_MS 50UL
#define SOUND_SAMPLE_INTERVAL_US 250UL
#define SOUND_IDLE_PERIOD_MS 1000UL
#define SOUND_THRESHOLD 90U

#define MPU6050_ADDRESS 0x68U
#define MPU_PITCH_OFFSET_DEG 0
#define MPU_ROLL_OFFSET_DEG 0
#define TILT_WARNING_DEG 30
#define TILT_CRITICAL_DEG 50
#define ROLLOVER_DEG 70

#define LIGHT_DARK_THRESHOLD 500U
#define LIGHT_ANALOG_DARK_BELOW 0
#define HEADLIGHT_ACTIVE_HIGH 1

#define BUZZER_ACTIVE_HIGH 1
#define CRITICAL_BEEP_MS 250UL

#define SCAN_SETTLE_MS 500UL
